### ISSUE TITLE
Boolean label and content props returning null

### ISSUE THREAD

**Issue by freakinhuge** [dailydrip/formulae_react#122]
When viewing a boolean (yes/no) question in the RespondToForm view, the label and content props seem to be returning null. When the checkbox is rendered it only shows the checkbox and no label or content strings.

**Comment by franzejr** [comment]
@freakinhuge,
I'm having trouble to reproducing this. Here everything is working (on the example app + formulae react). Can you give us an example of that error or give me access to your codebase? Thanks!
