### ISSUE TITLE
Certain fields are not persisting after saving a form

### ISSUE THREAD

**Issue by freakinhuge** [dailydrip/formulae_react#124]
I have noticed that the required field part of a component seems to not persist after it is created.
I have also noticed that when deleting existing choices from a multiple checkboxes component they do not persist.

**Comment by franzejr** [comment]
I only saw `I have also noticed that when deleting existing choices from a multiple checkboxes component they do not persist.` as a bug. I'm working on it.

**Comment by franzejr** [comment]
I fixed that on: https://github.com/dailydrip/formulae_react/commit/5582d2d339a6f610a9f0181d9a70ade375ab3d52
