### ISSUE TITLE
Inform the user when they've successfully submitted a form

### ISSUE THREAD

**Issue by knewter** [dailydrip/formulae_react#41]
We should thank the user for submitting the form and show a paragraph that the admin can configure to be shown after form submission.

/cc @cjarrett is there anything else here that we should do? Maybe this supports markdown? Just trying to figure it out so we finish it in one go...

**Comment by cjarrett** [comment]
@knewter I see markdown support being a plus here, but not necessary if it's a big lift.

**Comment by knewter** [comment]
@franzejr let's configure this as a property on the form. So this would mean:

- Add a `completion_content` field to the form in the API
- Add a `completionContent` field to the js record for the Form, and decode it from the API request.
- After completion, show `form.completionContent` - this means we likely also add a field to the `RespondToForm` state, outside of the form itself, that tracks whether the form has been submitted or not.
